config/routes.rb
Rails.application.routes.draw do
  resources :panels do
    resources :learn, only: [:index, :show]
    resources :cards
  end
  devise_for :users

  root to: 'panels#index'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :panel

  validates_presence_of :panel_id
  validates_presence_of :text, :translation
end

app/models/panel.rb
class Panel < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name, scope: [:user_id]
  has_many :cards
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :panels

  after_create :create_default_panel


  private
  def create_default_panel
    panels << Panel.create(name: "Default")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  def index
    @cards = Card.where(panel_id: params[:panel_id])
      .paginate(:page => params[:page], :per_page => 15)
  end

  # GET /cards/1
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @card.panel = Panel.find(params[:panel_id])
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to panel_cards_url(panel_id: params[:panel_id]), notice: 'Card was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cards/1
  def update

    if @card.update(card_params)
      redirect_to panel_cards_url(panel_id: params[:panel_id]), notice: 'Card was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cards/1
  def destroy
    @card.destroy
    redirect_to panel_cards_url, notice: 'Card was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def card_params
      params.require(:card).permit(:text, :translation, :panel_id)
    end
end

app/controllers/learn_controller.rb
class LearnController < ApplicationController
  def index
    @card = Card.where(panel_id: params[:panel_id]).first
  end

  def show
    @card = Card.find(params[:id])
    @card_next = Card.find_by(id: params[:id].next)
  end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_panel, only: [:show, :edit, :update, :destroy]

  # GET /panels
  def index
    @panels = Panel.all
  end

  # GET /panels/1
  def show
    @cards = @panel.cards
  end

  # GET /panels/new
  def new
    @panel = Panel.new
  end

  # GET /panels/1/edit
  def edit
  end

  # POST /panels
  def create
    @panel = Panel.new(panel_params)

    if @panel.save
      redirect_to @panel, notice: 'Panel was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /panels/1
  def update
    if @panel.update(panel_params)
      redirect_to @panel, notice: 'Panel was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /panels/1
  def destroy
    @panel.destroy
    redirect_to panels_url, notice: 'Panel was successfully destroyed.'
  end

  def learn
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.includes(:cards).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def panel_params
      params.require(:panel).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
    <ul>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>

      <ul class="footer-social">
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
          </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
        </a></li>
      </ul>
    </div>
</footer>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to 'Panels', panels_path %></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            <% end %>
            <li class="more"><a href="javascript:void(0)">Item with submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                <li><a href="javascript:void(0)">Another Item</a></li>
              </ul>
            </li>
            <li class="more"><a href="javascript:void(0)">Another submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                <li><a href="javascript:void(0)">An Item</a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
    </div>
  </div>
</header>

app/views/cards/_form.html.erb
<%= simple_form_for(@card, url: panel_cards_path, method: :post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :text, autofocus: true %>
    <%= f.input :translation %>
    <%= f.association :panel %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', panel_card_path %> |
<%= link_to 'Back', panel_cards_path %>

app/views/cards/index.html.erb
<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Translation</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.text %></td>
        <td><%= card.translation %></td>
        <td class="actions">
          <%= link_to 'Show', panel_card_path(card, panel_id: params[:panel_id]) %>
          <%= link_to 'Edit', edit_panel_card_path(card, panel_id: params[:panel_id]) %>
          <%= link_to 'Destroy', panel_card_path(card, panel_id: params[:panel_id]), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>

<br>

<%= link_to 'New Card', new_panel_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', panel_cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @card.text %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @card.translation %>
</p>

<%= link_to 'Edit', edit_panel_card_path(@card, panel_id: params[:panel_id]) %> |
<%= link_to 'Back', panel_cards_path %> |
<%= link_to 'New Card', new_panel_card_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <link rel="shortcut icon" href="/assets/icon.png">
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "navigation" %>
  <%= render "flashes" -%>
  <div class="main-container">
    <%= yield %>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/learn/index.html.erb
<%= link_to "Start learning", panel_learn_path(id: params[:panel_id]) %>

app/views/learn/show.html.erb
<div class="cards">
  <div class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-4.png" alt="">
    </div>
    <div class="card-header">
      Try!
    </div>
    <div class="card-copy">
      <p><%= @card.text %></p>
    </div>
    <div class="expander">
      <a href="javascript:void(0)" id="js-expander-trigger" class="expander-trigger expander-hidden" data-keybinding="c">
        <span class="shortcut">C</span>heck it!
      </a>
      <div id="js-expander-content" class="expander-content">
        <p><%= @card.translation %></p>
        <div class="actions">

          <div class="action">
            <%= link_to panel_learn_path(id: @card_next.id), data: { keybinding: 'k' } do %>
              I <span class="shortcut">k</span>now!
            <% end %>
          </div>
          <div class="action">
            <%= link_to panel_learn_path(id: @card_next.id), data: { keybinding: 'd' } do %>
              I <span class="shortcut">d</span>o not know :(
            <% end %>
          </div>
          <div class="action">
            <%= link_to panel_learn_path(id: @card_next.id), data: { keybinding: 'n' } do %>
              <span class="shortcut">N</span>ext card
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/panels/_cards.html.erb
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Translation</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.text %></td>
        <td><%= card.translation %></td>
        <td class="actions">
          <%= link_to 'Show', panel_card_path(card.id, panel_id: params[:id]) %>
          <%= link_to 'Edit', edit_panel_card_path(card.id, panel_id: params[:id]) %>
          <%= link_to 'Destroy', panel_card_path(card.id, panel_id: params[:id]), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/panels/_form.html.erb
<%= simple_form_for(@panel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/panels/edit.html.erb
<h1>Editing Panel</h1>

<%= render 'form' %>

<%= link_to 'Show', @panel %> |
<%= link_to 'Back', panels_path %>

app/views/panels/index.html.erb
<h1>Listing Panels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @panels.each do |panel| %>
      <tr>
        <td><%= link_to panel.name, panel %> (<%= panel.cards.count %>)</td>
        <td class="actions">
          <%= link_to 'Learn', panel_learn_index_path(panel), class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_panel_path(panel) %>
          <%= link_to 'Destroy', panel, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Panel', new_panel_path, class: "button" %>

app/views/panels/new.html.erb
<h1>New Panel</h1>

<%= render 'form' %>

<%= link_to 'Back', panels_path %>

app/views/panels/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @panel.name %>
</p>

<%= render "cards" %>

<%= link_to 'Add new Card', new_panel_card_path(params[:id]), class: 'button' %> |
<%= link_to 'Edit', edit_panel_path(@panel) %> |
<%= link_to 'Back', panels_path %>